# Generated by Django 3.1.1 on 2020-10-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20201008_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='categoria',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
