# Generated by Django 3.1.1 on 2020-10-08 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_auto_20201008_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='id_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.local'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.usuario'),
        ),
        migrations.AlterField(
            model_name='escaneos',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.usuario'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='id_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.local'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.usuario'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='id_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.local'),
        ),
        migrations.AlterField(
            model_name='notificaciones',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.usuario'),
        ),
        migrations.AlterField(
            model_name='rolpermiso',
            name='id_permiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.permiso'),
        ),
        migrations.AlterField(
            model_name='rolpermiso',
            name='id_rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.rol'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='id_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.local'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.rol'),
        ),
    ]
