# Generated by Django 3.1.1 on 2020-10-11 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_auto_20201008_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escaneos',
            name='celular',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.categoria'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
